package edu.fullerton.mobiledev.group5.gamefinder.database

import androidx.lifecycle.MutableLiveData
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey


@Entity(tableName = "profile_table")
data class Profile(

    // Defines the table's primary key. Primary keys are unique values that can be autogenerated.
    // They are used to differentiate one entity from another.
    @PrimaryKey(autoGenerate = true)
    var profileId: Long = 0L,

    // Non-rprimary key column. Data type is specified in the property.
    @ColumnInfo()
    var et_first_name: String = "",

    // Non-rprimary key column. Data type is specified in the property.
    @ColumnInfo()
    var et_last_name: String = "",

    // Non-rprimary key column. Data type is specified in the property.
    @ColumnInfo()
    var et_email: String = "",

    // Non-rprimary key column. Data type is specified in the property.
    @ColumnInfo()
    var et_password: String = "",

    // Non-rprimary key column. Data type is specified in the property.
    @ColumnInfo()
    var et_repeat_password: String = ""
)
